# Generated by Django 4.1.3 on 2022-11-16 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.FloatField(default=0.01, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('num_plays', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('explicit', models.BooleanField()),
            ],
        ),
    ]
