# Generated by Django 4.1.3 on 2022-11-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0002_artist_artistsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songs',
            field=models.ManyToManyField(through='jams.ArtistSong', to='jams.artist'),
        ),
    ]
