# Generated by Django 4.1.3 on 2022-11-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0003_song_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='artist_list', through='jams.ArtistSong', to='jams.artist'),
        ),
    ]
