# Generated by Django 4.1.3 on 2022-11-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0004_remove_song_songs_song_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='artistsong',
            unique_together={('artist', 'song')},
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.song')),
            ],
            options={
                'unique_together': {('album', 'song')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(related_name='album_list', through='jams.AlbumSong', to='jams.album'),
        ),
    ]
