# Generated by Django 4.1.3 on 2022-11-17 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jams', '0005_album_alter_artistsong_unique_together_albumsong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.genre')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jams.song')),
            ],
            options={
                'unique_together': {('genre', 'song')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(related_name='album_list', through='jams.GenreSong', to='jams.genre'),
        ),
    ]
